AP_UNITS = {
    "AP African American Studies": [
        "Unit 1: Origins of the African Diaspora",
        "Unit 2: Freedom, Enslavement, and Resistance",
        "Unit 3: The Practice of Freedom",
        "Unit 4: Movements and Debates",
    ],
    "AP Art History": [
        "Unit 1: Global Prehistory, 30,000-500 BCE",
        "Unit 2: Ancient Mediterranean, 3500 BCE-300 CE",
        "Unit 3: Early Europe and Colonial Americas, 200-1750 CE",
        "Unit 4: Later Europe and Americas, 1750-1980 CE",
        "Unit 5: Indigenous Americas, 1000 BCE-1980 CE",
        "Unit 6: Africa, 1100-1980 CE",
        "Unit 7: West and Central Asia, 500 BCE-1980 CE",
        "Unit 8: South, East, and Southeast Asia, 300 BCE-1980 CE",
        "Unit 9: The Pacific, 700-1980 CE",
        "Unit 10: Global Contemporary, 1980 CE to Present",
    ],
    "AP Biology": [
        "Unit 1: Chemistry of Life",
        "Unit 2: Cell Structure and Function",
        "Unit 3: Cellular Energetics",
        "Unit 4: Cell Communication and Cell Cycle",
        "Unit 5: Heredity",
        "Unit 6: Gene Expression and Regulation",
        "Unit 7: Natural Selection",
        "Unit 8: Ecology",
    ],
    "AP Calculus AB": [
        "Unit 1: Limits and Continuity",
        "Unit 2: Differentiation: Definition and Fundamental Properties",
        "Unit 3: Differentiation: Composite, Implicit, and Inverse Functions",
        "Unit 4: Contextual Applications of Differentiation",
        "Unit 5: Analytical Applications of Differentiation",
        "Unit 6: Integration and Accumulation of Change",
        "Unit 7: Differential Equations",
        "Unit 8: Applications of Integration",
    ],
    "AP Calculus BC": [
        "Unit 1: Limits and Continuity",
        "Unit 2: Differentiation: Definition and Fundamental Properties",
        "Unit 3: Differentiation: Composite, Implicit, and Inverse Functions",
        "Unit 4: Contextual Applications of Differentiation",
        "Unit 5: Analytical Applications of Differentiation",
        "Unit 6: Integration and Accumulation of Change",
        "Unit 7: Differential Equations",
        "Unit 8: Applications of Integration",
        "Unit 9: Parametric Equations, Polar Coordinates, and Vector-Valued Functions",
        "Unit 10: Infinite Sequences and Series",
    ],
    "AP Chemistry": [
        "Unit 1: Atomic Structure and Properties",
        "Unit 2: Molecular and Ionic Compound Structure and Properties",
        "Unit 3: Intermolecular Forces and Properties",
        "Unit 4: Chemical Reactions",
        "Unit 5: Kinetics",
        "Unit 6: Thermodynamics",
        "Unit 7: Equilibrium",
        "Unit 8: Acids and Bases",
        "Unit 9: Applications of Thermodynamics",
    ],
    "AP Chinese Language and Culture": [
        "Unit 1: Families in Different Societies",
        "Unit 2: The Influence of Language and Culture on Identity",
        "Unit 3: Influences of Beauty and Art",
        "Unit 4: How Science and Technology Affect Our Lives",
        "Unit 5: Factors That Impact the Quality of Life",
        "Unit 6: Environmental, Political, and Societal Challenges",
    ],
    "AP Comparative Government and Politics": [
        "Unit 1: Political Systems, Regimes, and Governments",
        "Unit 2: Political Institutions",
        "Unit 3: Political Culture and Participation",
        "Unit 4: Party and Electoral Systems and Citizen Organizations",
        "Unit 5: Political and Economic Changes and Development",
    ],
    "AP Computer Science A": [
        "Unit 1: Primitive Types",
        "Unit 2: Using Objects",
        "Unit 3: Boolean Expressions and if Statements",
        "Unit 4: Iteration",
        "Unit 5: Writing Classes",
        "Unit 6: Array",
        "Unit 7: ArrayList",
        "Unit 8: 2D Array",
        "Unit 9: Inheritance",
        "Unit 10: Recursion",
    ],
    "AP Computer Science Principles": [
        "Unit 1: Creative Development",
        "Unit 2: Data",
        "Unit 3: Algorithms and Programming",
        "Unit 4: Computer Systems and Networks",
        "Unit 5: Impact of Computing",
    ],
    "AP English Language and Composition": [
        "Unit 1: Claims, Reasoning, and Evidence",
        "Unit 2: Organizing Information for a Specific Audience",
        "Unit 3: Perspectives and How Writers Influence Readers",
        "Unit 4: How Writers Create Humor, Irony, and Satire",
        "Unit 5: Developing an Argument Through Choices in Writing",
        "Unit 6: Developing a Complex Argument",
        "Unit 7: Structuring and Supporting Coherent Arguments",
        "Unit 8: Stylistic Choices in Arguments",
        "Unit 9: Strategically Constructing Arguments",
    ],
    "AP English Literature and Composition": [
        "Unit 1: Short Fiction I",
        "Unit 2: Poetry I",
        "Unit 3: Longer Fiction or Drama I",
        "Unit 4: Short Fiction II",
        "Unit 5: Poetry II",
        "Unit 6: Longer Fiction or Drama II",
        "Unit 7: Short Fiction III",
        "Unit 8: Poetry III",
        "Unit 9: Longer Fiction or Drama III",
    ],
    "AP Environmental Science": [
        "Unit 1: The Living World: Ecosystems",
        "Unit 2: The Living World: Biodiversity",
        "Unit 3: Populations",
        "Unit 4: Earth Systems and Resources",
        "Unit 5: Land and Water Use",
        "Unit 6: Energy Resources and Consumption",
        "Unit 7: Atmospheric Pollution",
        "Unit 8: Aquatic and Terrestrial Pollution",
        "Unit 9: Global Change",
    ],
    "AP European History": [
        "Unit 1: Renaissance and Exploration",
        "Unit 2: Age of Reformation",
        "Unit 3: Absolutism and Constitutionalism",
        "Unit 4: Scientific, Philosophical, and Political Developments",
        "Unit 5: Conflict, Crisis, and Reaction in the Late 18th Century",
        "Unit 6: Industrialization and Its Effects",
        "Unit 7: 19th-Century Perspectives and Political Developments",
        "Unit 8: 20th-Century Global Conflicts",
        "Unit 9: Cold War and Contemporary Europe",
    ],
    "AP French Language and Culture": [
        "Unit 1: Families in Different Societies",
        "Unit 2: The Influence of Language and Culture on Identity",
        "Unit 3: Influences of Beauty and Art",
        "Unit 4: How Science and Technology Affect Our Lives",
        "Unit 5: Factors That Impact the Quality of Life",
        "Unit 6: Environmental, Political, and Societal Challenges",
    ],
    "AP German Language and Culture": [
        "Unit 1: Families in Different Societies",
        "Unit 2: The Influence of Language and Culture on Identity",
        "Unit 3: Influences of Beauty and Art",
        "Unit 4: How Science and Technology Affect Our Lives",
        "Unit 5: Factors That Impact the Quality of Life",
        "Unit 6: Environmental, Political, and Societal Challenges",
    ],
    "AP Human Geography": [
        "Unit 1: Thinking Geographically",
        "Unit 2: Population and Migration Patterns and Processes",
        "Unit 3: Cultural Patterns and Processes",
        "Unit 4: Political Patterns and Processes",
        "Unit 5: Agriculture and Rural Land-Use Patterns and Processes",
        "Unit 6: Cities and Urban Land-Use Patterns and Processes",
        "Unit 7: Industrial and Economic Development Patterns and Processes",
    ],
    "AP Italian Language and Culture": [
        "Unit 1: Families in Different Societies",
        "Unit 2: The Influence of Language and Culture on Identity",
        "Unit 3: Influences of Beauty and Art",
        "Unit 4: How Science and Technology Affect Our Lives",
        "Unit 5: Factors That Impact the Quality of Life",
        "Unit 6: Environmental, Political, and Societal Challenges",
    ],
    "AP Japanese Language and Culture": [
        "Unit 1: Families in Different Societies",
        "Unit 2: The Influence of Language and Culture on Identity",
        "Unit 3: Influences of Beauty and Art",
        "Unit 4: How Science and Technology Affect Our Lives",
        "Unit 5: Factors That Impact the Quality of Life",
        "Unit 6: Environmental, Political, and Societal Challenges",
    ],
    "AP Latin": [
        "Unit 1: Vergil, Aeneid, Book 1",
        "Unit 2: Caesar, Gallic War, Books 1 and 6",
        "Unit 3: Vergil, Aeneid, Book 2",
        "Unit 4: Caesar, Gallic War, Books 4 and 5",
        "Unit 5: Vergil, Aeneid, Books 4 and 6",
        "Unit 6: Caesar, Gallic War, Books 5 and 6",
        "Unit 7: Vergil, Aeneid, Books 6, 8, and 12",
        "Unit 8: Caesar, Gallic War, Book 5 (Part II)",
    ],
    "AP Macroeconomics": [
        "Unit 1: Basic Economic Concepts",
        "Unit 2: Economic Indicators and the Business Cycle",
        "Unit 3: National Income and Price Determination",
        "Unit 4: Financial Sector",
        "Unit 5: Long-Run Consequences of Stabilization Policies",
        "Unit 6: Open Economy - International Trade and Finance",
    ],
    "AP Microeconomics": [
        "Unit 1: Basic Economic Concepts",
        "Unit 2: Supply and Demand",
        "Unit 3: Production, Cost, and the Perfect Competition Model",
        "Unit 4: Imperfect Competition",
        "Unit 5: Factor Markets",
        "Unit 6: Market Failure and the Role of Government",
    ],
    "AP Music Theory": [
        "Unit 1: Music Fundamentals I: Pitch, Major Scales and Key Signatures, Rhythm, Meter, and Expressive Elements",
        "Unit 2: Music Fundamentals II: Minor Scales and Key Signatures, Melody, Timbre, and Texture",
        "Unit 3: Music Fundamentals III: Triads and Seventh Chords",
        "Unit 4: Harmony and Voice Leading I: Chord Function, Cadence, and Phrase",
        "Unit 5: Harmony and Voice Leading II: Chord Progressions and Predominant Function",
        "Unit 6: Harmony and Voice Leading III: Embellishments, Motives, and Melodic Devices",
        "Unit 7: Harmony and Voice Leading IV: Secondary Function",
        "Unit 8: Modes and Form",
    ],
    "AP Physics 1: Algebra-Based": [
        "Unit 1: Kinematics",
        "Unit 2: Dynamics",
        "Unit 3: Circular Motion and Gravitation",
        "Unit 4: Energy",
        "Unit 5: Momentum",
        "Unit 6: Simple Harmonic Motion",
        "Unit 7: Torque and Rotational Motion",
    ],
    "AP Physics 2: Algebra-Based": [
        "Unit 1: Fluids",
        "Unit 2: Thermodynamics",
        "Unit 3: Electric Force, Field, and Potential",
        "Unit 4: Electric Circuits",
        "Unit 5: Magnetism and Electromagnetic Induction",
        "Unit 6: Geometric and Physical Optics",
        "Unit 7: Quantum, Atomic, and Nuclear Physics",
    ],
    "AP Physics C: Electricity and Magnetism": [
        "Unit 1: Electrostatics",
        "Unit 2: Conductors, Capacitors, Dielectrics",
        "Unit 3: Electric Circuits",
        "Unit 4: Magnetic Fields",
        "Unit 5: Electromagnetism",
    ],
    "AP Physics C: Mechanics": [
        "Unit 1: Kinematics",
        "Unit 2: Newton's Laws of Motion",
        "Unit 3: Work, Energy, and Power",
        "Unit 4: Systems of Particles and Linear Momentum",
        "Unit 5: Rotation",
        "Unit 6: Oscillations",
        "Unit 7: Gravitation",
    ],
    "AP Precalculus": [
        "Unit 1: Polynomial and Rational Functions",
        "Unit 2: Exponential and Logarithmic Functions",
        "Unit 3: Trigonometric and Polar Functions",
        "Unit 4: Functions Involving Parameters, Vectors, and Matrices",
    ],
    "AP Psychology": [
        "Unit 1: Scientific Foundations of Psychology",
        "Unit 2: Biological Bases of Behavior",
        "Unit 3: Sensation and Perception",
        "Unit 4: Learning",
        "Unit 5: Cognitive Psychology",
        "Unit 6: Developmental Psychology",
        "Unit 7: Motivation, Emotion, and Personality",
        "Unit 8: Clinical Psychology",
        "Unit 9: Social Psychology",
    ],
    "AP Research": [
        "Section 1: Question and Explore",
        "Section 2: Understand and Analyze",
        "Section 3: Evaluate Multiple Perspectives",
        "Section 4: Synthesize Ideas",
        "Section 5: Academic Paper",
        "Section 6: Presentation and Oral Defense",
    ],
    "AP Seminar": [
        "Section 1: Question and Explore",
        "Section 2: Understand and Analyze Arguments",
        "Section 3: Evaluate Multiple Perspectives",
        "Section 4: Synthesize Ideas",
        "Section 5: Team Project and Presentation",
        "Section 6: Individual Research-Based Essay and Presentation",
    ],
    "AP Spanish Language and Culture": [
        "Unit 1: Families in Different Societies",
        "Unit 2: The Influence of Language and Culture on Identity",
        "Unit 3: Influences of Beauty and Art",
        "Unit 4: How Science and Technology Affect Our Lives",
        "Unit 5: Factors That Impact the Quality of Life",
        "Unit 6: Environmental, Political, and Societal Challenges",
    ],
    "AP Spanish Literature and Culture": [
        "Unit 1: La epoca medieval",
        "Unit 2: El Renacimiento y la epoca de oro",
        "Unit 3: El Siglo de las Luces e independencias americanas",
        "Unit 4: El Romanticismo, el Realismo y el Naturalismo",
        "Unit 5: La Generacion del 98 y el Modernismo",
        "Unit 6: Teatro y poesia del siglo XX",
        "Unit 7: El Boom latinoamericano",
        "Unit 8: Escritores contemporaneos de Estados Unidos y Espana",
    ],
    "AP Statistics": [
        "Unit 1: Exploring One-Variable Data",
        "Unit 2: Exploring Two-Variable Data",
        "Unit 3: Collecting Data",
        "Unit 4: Probability, Random Variables, and Probability Distributions",
        "Unit 5: Sampling Distributions",
        "Unit 6: Inference for Categorical Data: Proportions",
        "Unit 7: Inference for Quantitative Data: Means",
        "Unit 8: Inference for Categorical Data: Chi-Square",
        "Unit 9: Inference for Quantitative Data: Slopes",
    ],
    "AP Studio Art: 2-D Design": [
        "Section 1: Sustained Investigation (Selected Works)",
        "Section 2: Sustained Investigation (Writing)",
        "Section 3: Selected Works",
    ],
    "AP Studio Art: 3-D Design": [
        "Section 1: Sustained Investigation (Selected Works)",
        "Section 2: Sustained Investigation (Writing)",
        "Section 3: Selected Works",
    ],
    "AP Studio Art: Drawing": [
        "Section 1: Sustained Investigation (Selected Works)",
        "Section 2: Sustained Investigation (Writing)",
        "Section 3: Selected Works",
    ],
    "AP United States Government and Politics": [
        "Unit 1: Foundations of American Democracy",
        "Unit 2: Interactions Among Branches of Government",
        "Unit 3: Civil Liberties and Civil Rights",
        "Unit 4: American Political Ideologies and Beliefs",
        "Unit 5: Political Participation",
    ],
    "AP United States History": [
        "Unit 1: Period 1: 1491-1607",
        "Unit 2: Period 2: 1607-1754",
        "Unit 3: Period 3: 1754-1800",
        "Unit 4: Period 4: 1800-1848",
        "Unit 5: Period 5: 1844-1877",
        "Unit 6: Period 6: 1865-1898",
        "Unit 7: Period 7: 1890-1945",
        "Unit 8: Period 8: 1945-1980",
        "Unit 9: Period 9: 1980-Present",
    ],
    "AP World History: Modern": [
        "Unit 1: The Global Tapestry (1200-1450)",
        "Unit 2: Networks of Exchange (1200-1450)",
        "Unit 3: Land-Based Empires (1450-1750)",
        "Unit 4: Transoceanic Interconnections (1450-1750)",
        "Unit 5: Revolutions (1750-1900)",
        "Unit 6: Consequences of Industrialization (1750-1900)",
        "Unit 7: Global Conflict (1900-Present)",
        "Unit 8: Cold War and Decolonization (1900-Present)",
        "Unit 9: Globalization (1900-Present)",
    ],
}
